### ISSUE TITLE
Status URL fix

### ISSUE THREAD

**Issue by yonas** [rtucker/munin-lighttpd#1]
STATUS_URL = os.environ.get('statusurl', 'http://127.0.0.1/server-status?auto')

So that you can change in your munin config file

[lighttpd_*]
env.statusurl http://ip/other_status

Ref:
http://redmine.lighttpd.net/projects/lighttpd-sandbox/wiki/Howto_Munin

**Comment by rtucker** [comment]
Good call!  Fixed in commit 0637562bda9d5ced12b38aed9aa18ae420d67e79 and pushed.  Thank you!
