### ISSUE TITLE
bad exit from telnet but successful via command line

### ISSUE THREAD

**Issue by einkoro** [rtucker/munin-lighttpd#6]
On FreeBSD 9.0-RELEASE with munin 1.4.7 I can successfully execute lighttpd_ from the command line:

```
python lighttpd_kbytes 
data.value 56964
```

However no graphs are being generated and when I try it via telnet I encounter the following:

```
telnet localhost 4949
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
# munin node at xsgames01-dev
fetch lighttpd_kbytes
# Bad exit
.
```

From /var/log/munin/munin-node.log:

```
2012/09/04-15:04:22 CONNECT TCP Peer: "[127.0.0.1]:14975" Local: "[127.0.0.1]:4949"
Use of uninitialized value in pattern match (m//) at /usr/local/lib/perl5/site_perl/5.16.0/Net/Server.pm line 600.
2012/09/04-15:04:28 [20268] Error output from lighttpd_kbytes:
2012/09/04-15:04:28 [20268]     Can't exec "/usr/local/etc/munin/plugins/lighttpd_kbytes": No such file or directory at /usr/local/lib/perl5/site_perl/5.16.0/Munin/Node/Service.pm line 215, <STDIN> line 1.
2012/09/04-15:04:28 [20268]     # ERROR: Failed to exec.
2012/09/04-15:04:28 [20268] Service 'lighttpd_kbytes' exited with status 42/0.
```

The odd part is this occurs on two machines which are identical (production and development) but I have a 2nd set of machines with the same services and version of FreeBSD running that does not have this issue.

/usr/local/etc/munin/plugins:

```
lrwxr-xr-x  1 0  0  40 Sep  4 14:03 lighttpd_accesses -> /usr/local/share/munin/plugins/lighttpd_
lrwxr-xr-x  1 0  0  40 Sep  4 14:03 lighttpd_busyservers -> /usr/local/share/munin/plugins/lighttpd_
lrwxr-xr-x  1 0  0  40 Sep  4 14:03 lighttpd_idleservers -> /usr/local/share/munin/plugins/lighttpd_
lrwxr-xr-x  1 0  0  40 Sep  4 14:03 lighttpd_kbytes -> /usr/local/share/munin/plugins/lighttpd_
lrwxr-xr-x  1 0  0  40 Sep  4 14:03 lighttpd_uptime -> /usr/local/share/munin/plugins/lighttpd_
```

/usr/local/share/munin/plugins:

```
-rwxr-xr-x  1 0  0  4127 Sep  4 14:03 /usr/local/share/munin/plugins/lighttpd_
```

**Comment by einkoro** [comment]
Looks like the issue is a difference between the ports for python2.6 and 2.7 - there was a sym link for /usr/bin/python -> /usr/local/bin/python in 2.6 but not for 2.7

**Comment by rtucker** [comment]
Does replacing the hashbang line with:

```
#!/usr/bin/env python
```

make it work OK for both cases?  If so, then that's probably better than hard-coding /usr/bin/python.

**Comment by einkoro** [comment]
That appears to work over both sets of machines.

**Comment by rtucker** [comment]
I just committed a change that may help with that going forward.  Apologies for the inconvenience!
